
import java.awt.Toolkit;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ayush
 */
public class Between_Flight extends javax.swing.JFrame {

    /**
     * Creates new form Between_Flight
     */
    public Connection con=null;
    public ResultSet rs=null;
    public Statement stmt=null;
    public String id;
    public Between_Flight() {
        
        this.setResizable(true);
        initComponents();
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel16.setVisible(false);
        jLabel8.setVisible(false);
        jLabel19.setVisible(false);
        jLabel21.setVisible(false);
        jButton6.setVisible(false);
        Toolkit tk = Toolkit.getDefaultToolkit();
            //int xsize=(int) tk.getScreenSize().getWidth();
            //int ysize=(int) tk.getScreenSize().getWidth();
            this.setSize(1366, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find Flights Between Cities");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 38, 254, 174));

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Find Flights Between Cities");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 640, 103));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flight icon.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, 290));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel2.setText("Source");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 82, 50));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel5.setText("Destination");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, 44));

        jComboBox1.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Pune", "Delhi", "Mumbai", "Hyderabad", "Leh", "Bangalore", "Kochi", "Kolkata", "Goa", "Chennai", "Ranchi", "Jaipur", "Bagdogra", "Visakhapatnam", "Port Blair", "Patna", "Madurai", "Ahmedabad", "Trivandrum", "Lucknow" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 213, 50));

        jComboBox2.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Guwahati", "Srinagar", "Jammu", "Jaipur", "Amritsar", "Mumbai", "Delhi", "Goa", "Coimbatore", "Bangalore", "Ranchi", "Indore", "Hyderabad", "Chennai", "Nagpur", "Dehradun", "Trivandrum", "Kolkata", "Kochi", "Madurai", "Mangalore", "Udaipur", "Pune", "Bhopal", "Patna" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 213, 50));

        jButton1.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 238, 63));

        jButton2.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 204, 71));

        jButton3.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 165, 71));

        jButton4.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton4.setText("More");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, 186, 71));

        jButton5.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton5.setText("Search Again");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 190, 71));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baggage.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 285, 188));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 530, 232, 56));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rupee symbol.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 80, 100));

        jLabel17.setFont(new java.awt.Font("Bitstream Charter", 1, 72)); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 210, 70));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 240, 60));

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 460, 120));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 210, 60));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 140, 50));

        jLabel12.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 120, 60));

        jLabel13.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 180, 60));

        jLabel14.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(222, 17, 17));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 160, 60));

        jLabel15.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(24, 146, 25));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 170, 60));

        jLabel18.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 260, 80));

        jLabel19.setFont(new java.awt.Font("Bitstream Charter", 0, 36)); // NOI18N
        jLabel19.setText("Intermediate Flights");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 330, 60));

        jLabel20.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 470, 70));

        jLabel21.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel21.setText("(You can track your Flights by clicking the Track Flight Button. Please Note the Flight Numbers for future use.)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 880, 40));

        jButton6.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton6.setText("Track Flight");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, 240, 70));

        jLabel22.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 260, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        String args[]=new String[1];
        mainmenu.main(args);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat ft = new SimpleDateFormat ("E dd-MM-yyyy");
        Date dNow = new Date();
        String s;
        s=ft.format(dNow);
        jLabel22.setText(s);
        System.out.println(s);
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jLabel5.setVisible(false);
        jLabel2.setVisible(false);
        jButton1.setVisible(false);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel16.setVisible(true);
        jLabel8.setVisible(true);
        jLabel19.setVisible(true);
        jLabel21.setVisible(true);
        jButton6.setVisible(true);
        String source=jComboBox1.getSelectedItem().toString();
        String dest=jComboBox2.getSelectedItem().toString();
       // System.out.println(source+"\t"+dest);
        String query="SELECT * FROM flight_details WHERE Source LIKE '%"+(source)+"%' AND Destination LIKE '%"+(dest)+"%';";
      try
       {
            Class.forName("com.mysql.jdbc.Driver");
            con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","1");
            stmt = con.createStatement();
            rs=stmt.executeQuery(query);
            rs.last();
            id=rs.getString("id");
           //System.out.println(id);
            rs.first();
            //System.out.println(rs.getString("Flight Numbers"));
            jLabel7.setText(rs.getString("Baggage"));
            jLabel17.setText(rs.getString("Fare"));
             jLabel10.setText(rs.getString("Source").toUpperCase());
            jLabel9.setText(rs.getString("Destination").toUpperCase());
            jLabel11.setText(rs.getString("Duration"));
            jLabel12.setText(rs.getString("Source Code"));
            jLabel13.setText(rs.getString("Destination Code"));
            jLabel14.setText(rs.getString("Departure"));
            jLabel15.setText(rs.getString("Arrival"));
            jLabel18.setText(rs.getString("Class"));
            jLabel20.setText(rs.getString("Flight Numbers"));
       }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(this,e.getMessage());
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            rs.next();
            String i=rs.getString("id");
            if(i.equals(id))
            {
                jButton4.setVisible(false);
            }
            //System.out.println(rs.getString("Flight Numbers"));
            jLabel7.setText(rs.getString("Baggage"));
            jLabel17.setText(rs.getString("Fare"));
            jLabel10.setText(rs.getString("Source").toUpperCase());
            jLabel9.setText(rs.getString("Destination").toUpperCase());
            jLabel11.setText(rs.getString("Duration"));
            jLabel12.setText(rs.getString("Source Code"));
            jLabel13.setText(rs.getString("Destination Code"));
            jLabel14.setText(rs.getString("Departure"));
            jLabel15.setText(rs.getString("Arrival"));
            jLabel18.setText(rs.getString("Class"));
            jLabel20.setText(rs.getString("Flight Numbers"));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here
        setVisible(false);
        String args[]=new String[1];
        main(args);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        String args[]=new String[1];
        Know_Flight.main(args);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Between_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Between_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Between_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Between_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Between_Flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
