
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ayush
 */
public class Know_Flight extends javax.swing.JFrame {

    /**
     * Creates new form Know_Flight
     */
    public Know_Flight() {
        //this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(true);
        //this.setVisible(true);
        initComponents();
        jLabel7.setVisible(false);
        jLabel16.setVisible(false);
        jLabel18.setVisible(false);
        jButton2.setVisible(false);
        Toolkit tk = Toolkit.getDefaultToolkit();
            //int xsize=(int) tk.getScreenSize().getWidth();
            //int ysize=(int) tk.getScreenSize().getWidth();
            this.setSize(1366, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Your Flight");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 254, 174));

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 48)); // NOI18N
        jLabel1.setText("TRACK YOUR FLIGHT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 511, 83));

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel2.setText("Enter Flight Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 250, 40));

        jTextField1.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 220, 40));

        jButton1.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 260, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flight icon.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, -1, 290));

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 300, 70));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 240, 60));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 210, 60));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 460, 120));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 470, 50));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 120, 60));

        jLabel12.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 180, 60));

        jLabel13.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(24, 146, 25));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 170, 60));

        jLabel14.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(222, 17, 17));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 160, 60));

        jLabel15.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 260, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rupee symbol.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 80, 100));

        jLabel17.setFont(new java.awt.Font("Bitstream Charter", 1, 72)); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 210, 70));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 400, 220));

        jButton2.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton2.setText("Track Another Flight");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 270, 80));

        jButton3.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 240, 80));

        jButton4.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 560, 240, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fno;
        fno=jTextField1.getText().toUpperCase();
       jButton1.setVisible(false);
       jTextField1.setVisible(false);
       jLabel2.setVisible(false);
       jLabel7.setVisible(true);
       jLabel16.setVisible(true);
       jLabel18.setVisible(true);
       jButton2.setVisible(true);
       String query="SELECT * FROM flight_number WHERE `Flight No`='"+(fno)+"'";
       //System.out.println(query);
       try
       {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","1");
            Statement stmt;
            stmt = con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                String flightno,airlines,source,source_code,dest,dest_code,dur,dept_time,arr_time,classtype,fare;
                flightno = rs.getString("Flight No");
                jLabel6.setText(flightno);
                airlines=rs.getString("Airlines").toUpperCase();
                ImageIcon ii;
                switch(airlines)
                {
                    case "INDIGO": ii = new ImageIcon(getClass().getResource("/IndiGo_Logo.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "AIR INDIA":ii = new ImageIcon(getClass().getResource("/air india.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "GO AIR":ii = new ImageIcon(getClass().getResource("/GoAir.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "JET AIRWAYS":ii = new ImageIcon(getClass().getResource("/jet airways.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "SPICEJET":ii = new ImageIcon(getClass().getResource("/spicejet1.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "AIRASIA INDIA": ii= new ImageIcon(getClass().getResource("/air asia.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "VISTARA":ii= new ImageIcon(getClass().getResource("/vistara.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "AIR COASTA":ii= new ImageIcon(getClass().getResource("/air costa.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                    case "AIR PEGASUS":ii= new ImageIcon(getClass().getResource("/pegasus.png"));
                                        jLabel18.setIcon(ii);
                                        break;
                }
                source=rs.getString("Source").toUpperCase();
                jLabel10.setText(source);
                source_code=rs.getString("Source Code");
                jLabel11.setText("("+source_code+")");
                dest=rs.getString("Destination").toUpperCase();
                jLabel5.setText(dest);
                dest_code=rs.getString("Destination Code");
                jLabel12.setText("("+dest_code+")");
                dur=rs.getString("Duration");
                jLabel9.setText(dur);
                dept_time=rs.getString("Departure Time");
                jLabel14.setText(dept_time);
                arr_time=rs.getString("Arrival Time");
                jLabel13.setText(arr_time);
                classtype=rs.getString("Class");
                jLabel15.setText(classtype);
                fare=rs.getString("Fare");
                if("0".equals(fare))
                {
                    fare=" N/A";
                }
                jLabel17.setText(fare);
                //System.out.println(flightno+" "+airlines+" "+source+" "+source_code+" "+dest+" "+dest_code+" "+dur+" "+dept_time+" "+arr_time+" "+classtype+" "+fare);
            }
       }
       catch(Exception e)
       {
            JOptionPane.showMessageDialog(this,e.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        main(args);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        setVisible(false);
        mainmenu.main(args);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Know_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Know_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Know_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Know_Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Know_Flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
